name: ghosts-cpu
channels:
  - huggingface
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cachetools=5.3.3
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cpuonly=2.0
  - cryptography=42.0.5
  - dataclasses=0.8
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - huggingface_hub=0.23.3
  - idna=3.7
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - joblib=1.4.0
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=3.0.13
  - opt_einsum=3.3.0
  - packaging=23.2
  - pillow=9.0.1
  - pip=24.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-flatbuffers=2.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.10.3
  - requests=2.32.2
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - sacremoses=master
  - scipy=1.11.4
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - termcolor=2.1.0
  - tk=8.6.14
  - tokenizers=0.10.3
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm=4.66.4
  - transformers=4.14.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aitextgen==0.5.1
      - bidict==0.23.1
      - deprecated==1.2.14
      - dnspython==2.6.1
      - eventlet==0.33.3
      - fire==0.6.0
      - flask==2.1.2
      - flask-socketio==5.1.2
      - fsspec==2024.6.0
      - greenlet==3.0.3
      - h11==0.14.0
      - hurry-filesize==0.9
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - lightning-utilities==0.11.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - python-dotenv==0.20.0
      - python-engineio==4.9.1
      - python-socketio==5.11.2
      - pytorch-lightning==1.9.4
      - redis==4.3.2
      - shortuuid==1.0.8
      - simple-websocket==1.0.0
      - sympy==1.12.1
      - torch==2.3.1
      - torchmetrics==1.4.0.post0
      - triton==2.3.1
      - walrus==0.9.1
      - werkzeug==2.2.2
      - wsproto==1.2.0
