#!/bin/bash

# build static site
cd serve/site
npm run build
cd ../..

# database
redis-server redis.conf

# server
conda run -n ghosts-cpu python3 serve/app.py &

# generator
conda run -n ghosts-cpu python3 generate/generator.py
